language: python
python:
- '3.3'
- '3.4'
install: true
script:
- nosetests tests.py
env:
  global:
  - secure: ZfUUQHwUu2P9/IkrPbxF6oTbBZhV411dy0cKnbdlkACHypQLp7619lqgp7zRbennvxdyro2zJG7tJ/vWrp8DAI1Mo5vUn5px/giN/CBj+9Qz5VH8cK95ndKC3nfFGrLucKqoMTVe7GhcTHp8ytC+xF39dR1vJOraQLPUwHektC0=
  - secure: IoQ7Gogb49Li0RkA9rcsumQq4oJR42tId9JYLxr/Th92lbTcZ5PyLGDeNXgqyrWYv5kAh0pFFX69POm/u+ivekY+iDia37HTJmTqnHpEfjX9TsXEHvngXDsNOnJkwlW1yXPJKFiTlVZkRDM7s6C48Uy5uXOpD0v+zKF/TNEg+TM=
  - secure: rKT7bXVCRIrSsdLQH7YkTOVYLcIzfxGaDZldlQtETx3mdRtPVk1n8cjE+q+O3egmV15yOGJfwG3UMf3shFZZXIFGSgz6AqA/B+XM5UkVMbrPaycNYg4a4Mm8P5s6B0AD5cqu3/ljCWL41uAi1F6Jol06PCtswaahJpyC7sdsHKo=
